GET http://localhost:3001/api/v1/

###
POST http://localhost:3001/api/v1/
Content-Type: application/json

{
	"name": "task 2",
	"important": false
}

###
DELETE http://localhost:3001/api/v1/61185bf6c0de2458478aac8a

###
PUT http://localhost:3001/api/v1/61185c21cc03ac587d685257
Content-Type: application/json

{
	"name": "task 1",
	"important": true,
	"completed": false
}
